# -*- coding: utf-8 -*-
"""TDS assignment8b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bSoTcMYHCYpw6P4IUeqB0s4BJqz2O_r4
"""

import streamlit as st

def main():
    # Set the page configuration
    st.set_page_config(page_title="Largest Number", page_icon=":1234:")

    # Display the title and explanation
    st.title("Find the Largest Number")
    st.write("Enter three numbers and find the largest of the three.")

    # Get the user inputs
    num1 = st.number_input("Enter the first number:")
    num2 = st.number_input("Enter the second number:")
    num3 = st.number_input("Enter the third number:")

    # Find the largest number
    largest_num = max(num1, num2, num3)

    # Display the largest number
    st.write("The largest number is:", largest_num)


if __name__ == "__main__":
    main()

